### ISSUE TITLE
Need some help on watchOS

### ISSUE THREAD

**Issue by kekko7072** [michaelhitzker/flutter-vikings-2022#1]
Hey great project and talk, very impressive and helpful.

I need some help with watchOS because it shows only loading and it's not showing of numbers of coffe etc, but the buttons are working.  ![IMG_0417 copia](https://user-images.githubusercontent.com/32552589/196871953-e1381e60-49a5-415e-9eb9-40121a1eaf95.png)

To run it on a real iPhone and Apple Watch I needed to enable bit code in shared preferences pod file. And I run in profile mode the iOS app.

Thanks.

**Comment by michaelhitzker** [comment]
Hi Francesco! Glad you like the project and thx for reaching out. Unfortunately, I'm busy this weekend but I'll come back to you next week

**Comment by kekko7072** [comment]
Hey @michaelhitzker any updates ?

**Comment by kekko7072** [comment]
More info, I downloaded the code, changed the sign in and run the example. From watch to app I can see the increased value of beers and coffe but in the watch I see only loading on the counters.
When I run the watchOS app it says:
 `watch WatchKit Extension[16137:113941] void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL`

**Comment by kekko7072** [comment]
@michaelhitzker hey how are you? Any update?
